import 'package:flutter/material.dart';

const defaultStoreIcon = Icons.store;

const storeIconMap = <String, IconData>{
  'store': Icons.store,
  'storefront': Icons.storefront,
  'market': Icons.storefront_outlined,
  'supermarket': Icons.local_grocery_store,
  'convenience': Icons.local_convenience_store,
  'cart': Icons.shopping_cart,
  'basket': Icons.shopping_basket,
  'shopping': Icons.shopping_bag,
  'online': Icons.shopping_cart_checkout,
  'warehouse': Icons.warehouse,
  'pharmacy': Icons.local_pharmacy,
  'health': Icons.medication,
  'bakery': Icons.bakery_dining,
  'butcher': Icons.kebab_dining,
  'seafood': Icons.set_meal,
  'produce': Icons.eco,
  'garden': Icons.grass,
  'florist': Icons.local_florist,
  'hardware': Icons.hardware,
  'tools': Icons.handyman,
  'wrench': Icons.build,
  'electronics': Icons.devices,
  'phone': Icons.smartphone,
  'clothing': Icons.checkroom,
  'shoes': Icons.hiking,
  'furniture': Icons.weekend,
  'homegoods': Icons.chair,
  'home': Icons.home,
  'books': Icons.menu_book,
  'toys': Icons.toys,
  'pets': Icons.pets,
  'liquor': Icons.liquor,
  'coffee': Icons.local_cafe,
  'gas': Icons.local_gas_station,
  'gift': Icons.card_giftcard,
  'jewelry': Icons.diamond,
  'sports': Icons.sports_basketball,
  'beauty': Icons.brush,
  'office': Icons.work,
  'baby': Icons.child_friendly,
  'deli': Icons.restaurant,
};

IconData storeIcon(String? key) => storeIconMap[key ?? ''] ?? defaultStoreIcon;
