import 'package:flutter/material.dart';

import 'package:pantry_core/utils/entity_icons.dart';

/// Icon shown for an unknown/unset label key — the generic label glyph.
const defaultLabelIcon = EntityIcons.label;

/// `key → IconData` for the label icon palette, ported from the web's
/// `LABEL_ICONS` (`src/components/LabelPicker/labelIcons.ts`). The keys are the
/// server-owned set (`ConstantsService::LABEL_ICON_KEYS`); unknown keys fall
/// back to [defaultLabelIcon] via [labelIcon]. Distinct from the category and
/// store palettes.
const labelIconMap = <String, IconData>{
  'tag': Icons.sell,
  'tag-multiple': Icons.local_offer,
  'tag-heart': Icons.loyalty,
  'tag-plus': Icons.new_label,
  'label': Icons.label,
  'label-multiple': Icons.style,
  'star': Icons.star,
  'heart': Icons.favorite,
  'fire': Icons.local_fire_department,
  'flash': Icons.flash_on,
  'lightning-bolt': Icons.bolt,
  'priority-high': Icons.priority_high,
  'priority-low': Icons.low_priority,
  'alert': Icons.warning,
  'alert-circle': Icons.error,
  'information': Icons.info,
  'check-circle': Icons.check_circle,
  'close-circle': Icons.cancel,
  'clock': Icons.access_time,
  'calendar': Icons.calendar_today,
  'bell': Icons.notifications,
  'flag': Icons.flag,
  'bookmark': Icons.bookmark,
  'pin': Icons.push_pin,
  'map-marker': Icons.place,
  'gift': Icons.card_giftcard,
  'sale': Icons.local_offer,
  'percent': Icons.percent,
  'currency-usd': Icons.attach_money,
  'cart': Icons.shopping_cart,
  'basket': Icons.shopping_basket,
  'truck': Icons.local_shipping,
  'ticket': Icons.confirmation_number,
  'barcode': Icons.qr_code,
  'seal': Icons.verified,
  'leaf': Icons.eco,
  'sprout': Icons.grass,
  'recycle': Icons.recycling,
  'snowflake': Icons.ac_unit,
  'water': Icons.water_drop,
  'food-apple': Icons.apple,
  'silverware': Icons.restaurant,
  'cup': Icons.local_cafe,
  'pill': Icons.medication,
  'medical-bag': Icons.medical_services,
  'paw': Icons.pets,
  'baby': Icons.child_friendly,
  'home': Icons.home,
  'briefcase': Icons.work,
  'school': Icons.school,
  'palette': Icons.palette,
  'music': Icons.music_note,
  'camera': Icons.camera_alt,
  'gamepad': Icons.sports_esports,
  'run': Icons.directions_run,
  'dumbbell': Icons.fitness_center,
  'wrench': Icons.build,
  'new-box': Icons.fiber_new,
  'sticker': Icons.sticky_note_2,
  'thumb-up': Icons.thumb_up,
  'eye': Icons.visibility,
  'lock': Icons.lock,
  'key': Icons.key,
  'shield': Icons.shield,
  'diamond': Icons.diamond,
  'crown': Icons.workspace_premium,
  'rocket': Icons.rocket_launch,
  'bug': Icons.bug_report,
  'puzzle': Icons.extension,
  'feather': Icons.history_edu,
  'bullhorn': Icons.campaign,
  'creation': Icons.auto_awesome,
  'star-shooting': Icons.trending_up,
};

IconData labelIcon(String? key) => labelIconMap[key ?? ''] ?? defaultLabelIcon;
